wget -O "merv.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AIM25&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "come.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3ACOME&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "edn.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AEDN&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "ggal.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AGGAL&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "indu.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AINDU&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "apbr.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AAPBR&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "erar.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AERAR&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "ts.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3ATS&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "ypf.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AYPFD&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "pamp.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3APAMP&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "mirg.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AMIRG&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "alua.ba.csv" "http://www.google.com/finance/historical?q=BCBA%3AALUA&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"


wget -O "ggal.adr.csv" "http://www.google.com/finance/historical?q=NASDAQ%3AGGAL&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
wget -O "pbr.adr.csv" "http://www.google.com/finance/historical?q=NYSE%3APBR&ei=1OUeVOi8GIrKsQetp4GoCg&output=csv"
